version: '3.4'
services:
  command:
    image: syscomiddleware/commander-command
    ports:
      - 5050:8080
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_GROUP: activity-command
      HOST_ADDRESS: :8080
      COMMANDER_EVENT_TOPIC: activity-events
      COMMANDER_COMMAND_TOPIC: activity-commands
    networks:
      - kafka
networks:
  kafka:
    external:
      name: kafka
