version: '3.4'
services:
  command:
    image: syscomiddleware/commander-command
    ports:
      - 6060:8080
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_GROUP: cart-command
      HOST_ADDRESS: :8080
      COMMANDER_EVENT_TOPIC: cart-events
      COMMANDER_COMMAND_TOPIC: cart-commands
    networks:
      - kafka
networks:
  kafka:
    external:
      name: kafka
